import Head from 'next/head'
import dynamic from 'next/dynamic'
import { useState } from 'react'

const MoonScene = dynamic(() => import('../components/MoonScene'), { ssr: false })

export default function Home() {
  const [showTerms, setShowTerms] = useState(false)

  return (
    <>
      <Head>
        <title>Lunar Pre-Emptive Rights</title>
        <meta name="description" content="Reserve speculative pre-emptive lunar land positions tied to coordinates." />
        <meta name="keywords" content="moon land, lunar property, space law, moon ownership, lunar parcels" />
        <meta property="og:title" content="Lunar Pre-Emptive Rights" />
        <meta property="og:description" content="Humanity is returning to the Moon. Laws will follow." />
      </Head>

      <header className="header">
        🌕 Lunar Pre-Emptive Rights
      </header>

      <MoonScene />

      <button className="terms-toggle" onClick={() => setShowTerms(!showTerms)}>
        {showTerms ? 'Hide Terms & Conditions' : 'Show Terms & Conditions'}
      </button>

      {showTerms && (
        <div className="terms">
          <p>
            This platform provides a symbolic, speculative reservation linked to
            lunar coordinates. No ownership or legal property rights are granted
            under current international law (Outer Space Treaty, 1967).
          </p>
          <p>
            Documentation generated by this service may be referenced if future
            international legal frameworks permit private or commercial lunar claims.
          </p>
        </div>
      )}

      <div className="social">
        <a href="https://facebook.com" target="_blank">
          <img src="/fb.png" />
        </a>
        <a href="https://instagram.com" target="_blank">
          <img src="/insta.png" />
        </a>
        <a href="https://twitter.com" target="_blank">
          <img src="/x.png" />
        </a>
      </div>

      <footer>© 2026 Lunar Pre-Emptive Rights</footer>
    </>
  )
}
